language: node_js
sudo: false
node_js:
  - '5'
git:
  depth: 5
addons:
  sauce_connect:
    username: stremann
    access_key:
      secure: Z30ZbeCIE0+72c/jFUA3lmzXljVmRIEX+wkE8L9hxHFPDOEktgDxlCwNKwr8fDbYopoJew0KITSTJmDskMlERF4qcF4bCoBK8T6++363g6ryzEEOINrc0CcJgS1fnXrjvSgLfQMN6a4uSUqwONOc2P8IlCKjKQHIfiu013xFhKuVbq+qWULUqumoGfleCdGKg0XmHFHxbhD+8st3GD5JAApIQxKF/f/wdENpONfA7GOxh+LOql/pc/od97WJXjDFV3LIH4c9JVsojs7iXLBMSWMWqRDexO4WMCx5b6Hpgz0VqELw9ULn7f6fNt6ZZ/r2A7+FqBG1dO+0uSkBTNlYCuTAMIpqS3OcZvJ+q5FKdKf5QLZ5JHAYooq+Qn2rEdVJ84HIjhiGZY+FRU/0+MphkNp7yHo1hpuYuuFovUT+Lw8oPTCSzff93C1+BZ+P4jj0xWWQRn0wr4f+KhCw+ptLJAcDHGhmgGg262ojLrEDamiXTBE+UD5SgfloWp946RSa8Qos48dHM+dwSXGii7/DJuRgeBkBX0rOI8EjJCRwojCKq7Viq8VcldXZXReInuEnUI0hNA1Z4vKjmiQETgtH1Nqxcb8/rMLcSkcYDj0A5MT6TP8jlOJAS7AlbAsyMxA9wBJRhrQMtdF7NhKmTtRD5hLnY0qwcBygBM75d19QnRs=
script:
  - npm run build
  - npm test
  - npm run selenium-install
  - npm run selenium-start &
  - sleep 1
  - USE_SAUCE=true BROWSER=chrome npm run uitest
branches:
  only:
    - master
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: YHBT3sqo1xtGG+THDOenxQP8vnb+D43luWPzP3rv+Oa8kyo+bTUOMUdeJOl2uoM2XvlToEM7hOJbWEgaVPjomJ3/HFMSW2PAsfBcUYYJDOQ43t/wehJpPX/+ALdZuWUs+lzAsL31WTxTkyYn5HfiE6T406gtbY05sBx1AQBcvXQW/1IIDCMljxKnLdmpET9IAS3SHIjKBI2nF6f2LVghUkXKU6v9xhYgw8Jt998dv/mlWoYHhUDqw3Vk913ce+EQljguPxSy5FKdEOBwyxu0Bqh9GVGaUe+YpWnVP6u0kMqehjfEog0wNMu1ly4cIrXQTrWAfrHEU3dduFda2k0sarBOLeOQvjveM11nw1CANt9hwViOsFfWpteIDuZLTYx8F2hMj0kEkmFCloCa8yh9VrrVY+06i0SjLlKeub2o2M4jjc4m6RWOgjZYdoVCPnlz85TEdcQ/BBf6Uxuxs13oauQRFQgqVqC9SXojeTnUyiIc8YNEy8dAXggFkL7GXWV+G4Y5tbcVYaPaKezWN6wvDmd9ikZ1bYLhRSezMsb5cnSM1KTlk2DaD712s+auXqVcSMMoBfuvvazixf2CyuTIAaKo92egVjxphgXWAsBb4udethBAL8A6CRvykBzqAGaV2NWasNjA4tLrpR9asVw4enQKDbvlwEziSI54a2gCbOM=
